### ISSUE TITLE
Reveal.js theme?

### ISSUE THREAD

**Issue by adamhsparks** [AAGI-AUS/AAGITemplates#7]
I've used Quarto/Reveal.js earlier this year, https://codeberg.org/adamhsparks/IEW13, and found it rather nice. Could we have a theme for Reveal.js as well?

**Comment by rogerssam** [comment]
Looks like quarto doesn't support xaringan (remark.js) so I reckon we'll have to port to reveal when we do the quarto templates.

**Comment by adamhsparks** [comment]
I'll close this issue with this repo that's rapidly maturing: https://github.com/AAGI-AUS/AAGIQuarto
